apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
    name: hello
  namespace: hello-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      name: hello
  template:
    metadata:
      labels:
        app: hello
        name: hello
    spec:
      containers:
      - name: hello
        image: quay.io/harpasin/do480-hello-nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
    name: hello
  name: hello
  namespace: hello-app
spec:
  ports:
  - port: 8080
  selector:
    name: hello
---
kind: Route
apiVersion: v1
metadata:
  name: hello-app
  labels:
    app: hello
    name: hello
  namespace: hello-app  
spec:
  # Replace the entry with the value of your wildcard domain.
  host: hello.apps.ocp4-mng.example.com
  subdomain: ''
  to:
    kind: Service
    name: hello
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
